### ISSUE TITLE
Proper use of "someday"

### ISSUE THREAD

**Issue by evilham** [AnotherKamila/tasksched#22]
When using `someday` on taskwarrior, it actually uses +20 years, maybe we want to show any tasks due/scheduled further than 10 years in the future as due/scheduled "someday"

**Comment by robertbasden** [comment]
I would be interested in taking a look at this - if thats ok?

**Comment by evilham** [comment]
(take the hearts as a "YES!" :-D)

**Comment by AnotherKamila** [comment]
@robertbasden That would be very welcome! If you need any help, just ask :-)

**Comment by robertbasden** [comment]
Nice!! I'll have a look and shout if any questions.

**Comment by robertbasden** [comment]
Added a PR: https://github.com/AnotherKamila/tasksched/pull/23 please let me know any feedback / changes or anything!
